name: Sync with Upstream

on:
    schedule:
        - cron: "0 */36 * * *"

jobs:
    sync:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Fetch upstream changes
              run: git fetch upstream

            - name: Merge upstream/main into upstream branch
              run: git merge upstream/main

            - name: Push changes to upstream branch
              run: |
                  git config --global user.name 'GitHub Actions'
                  git config --global user.email 'actions@users.noreply.github.com'
                  git push origin HEAD:upstream
